// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_softmax
NumericVector cpp_softmax(NumericVector u, bool log);
RcppExport SEXP _choicedata_cpp_softmax(SEXP uSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_softmax(u, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_logsumexp
double cpp_logsumexp(NumericVector x);
RcppExport SEXP _choicedata_cpp_logsumexp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_logsumexp(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ologit
NumericVector cpp_ologit(NumericVector v, NumericVector gamma, IntegerVector y, bool log);
RcppExport SEXP _choicedata_cpp_ologit(SEXP vSEXP, SEXP gammaSEXP, SEXP ySEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ologit(v, gamma, y, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ologit_all
NumericMatrix cpp_ologit_all(NumericVector v, NumericVector gamma);
RcppExport SEXP _choicedata_cpp_ologit_all(SEXP vSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ologit_all(v, gamma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ranked_logit
double cpp_ranked_logit(NumericVector u, IntegerVector ranking, bool log);
RcppExport SEXP _choicedata_cpp_ranked_logit(SEXP uSEXP, SEXP rankingSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type u(uSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ranking(rankingSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ranked_logit(u, ranking, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mnl_chosen
NumericVector cpp_mnl_chosen(List x, List y, NumericVector beta, bool ranked, bool log);
RcppExport SEXP _choicedata_cpp_mnl_chosen(SEXP xSEXP, SEXP ySEXP, SEXP betaSEXP, SEXP rankedSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type ranked(rankedSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mnl_chosen(x, y, beta, ranked, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mnl_all
NumericMatrix cpp_mnl_all(List x, NumericVector beta, bool log);
RcppExport SEXP _choicedata_cpp_mnl_all(SEXP xSEXP, SEXP betaSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mnl_all(x, beta, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_panel_prod
NumericVector cpp_panel_prod(NumericVector p, IntegerVector tp, bool log, bool input_log);
RcppExport SEXP _choicedata_cpp_panel_prod(SEXP pSEXP, SEXP tpSEXP, SEXP logSEXP, SEXP input_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    Rcpp::traits::input_parameter< bool >::type input_log(input_logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_panel_prod(p, tp, log, input_log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_average_draws
NumericVector cpp_average_draws(NumericMatrix draws, NumericVector beta, IntegerVector position, Function compute, bool log);
RcppExport SEXP _choicedata_cpp_average_draws(SEXP drawsSEXP, SEXP betaSEXP, SEXP positionSEXP, SEXP computeSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type draws(drawsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type position(positionSEXP);
    Rcpp::traits::input_parameter< Function >::type compute(computeSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_average_draws(draws, beta, position, compute, log));
    return rcpp_result_gen;
END_RCPP
}
// cpp_probit_d
List cpp_probit_d(NumericVector v, IntegerVector y, bool ranked);
RcppExport SEXP _choicedata_cpp_probit_d(SEXP vSEXP, SEXP ySEXP, SEXP rankedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type ranked(rankedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_probit_d(v, y, ranked));
    return rcpp_result_gen;
END_RCPP
}
// cpp_probit_cov
List cpp_probit_cov(NumericMatrix x, NumericMatrix omega, NumericMatrix sigma, NumericMatrix d, int occasions);
RcppExport SEXP _choicedata_cpp_probit_cov(SEXP xSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP dSEXP, SEXP occasionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type occasions(occasionsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_probit_cov(x, omega, sigma, d, occasions));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cml_chunks
List cpp_cml_chunks(int tp, int block, int type);
RcppExport SEXP _choicedata_cpp_cml_chunks(SEXP tpSEXP, SEXP blockSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< int >::type block(blockSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cml_chunks(tp, block, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_prob_prod
double cpp_prob_prod(NumericVector p, bool log);
RcppExport SEXP _choicedata_cpp_prob_prod(SEXP pSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_prob_prod(p, log));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_choicedata_cpp_softmax", (DL_FUNC) &_choicedata_cpp_softmax, 2},
    {"_choicedata_cpp_logsumexp", (DL_FUNC) &_choicedata_cpp_logsumexp, 1},
    {"_choicedata_cpp_ologit", (DL_FUNC) &_choicedata_cpp_ologit, 4},
    {"_choicedata_cpp_ologit_all", (DL_FUNC) &_choicedata_cpp_ologit_all, 2},
    {"_choicedata_cpp_ranked_logit", (DL_FUNC) &_choicedata_cpp_ranked_logit, 3},
    {"_choicedata_cpp_mnl_chosen", (DL_FUNC) &_choicedata_cpp_mnl_chosen, 5},
    {"_choicedata_cpp_mnl_all", (DL_FUNC) &_choicedata_cpp_mnl_all, 3},
    {"_choicedata_cpp_panel_prod", (DL_FUNC) &_choicedata_cpp_panel_prod, 4},
    {"_choicedata_cpp_average_draws", (DL_FUNC) &_choicedata_cpp_average_draws, 5},
    {"_choicedata_cpp_probit_d", (DL_FUNC) &_choicedata_cpp_probit_d, 3},
    {"_choicedata_cpp_probit_cov", (DL_FUNC) &_choicedata_cpp_probit_cov, 5},
    {"_choicedata_cpp_cml_chunks", (DL_FUNC) &_choicedata_cpp_cml_chunks, 3},
    {"_choicedata_cpp_prob_prod", (DL_FUNC) &_choicedata_cpp_prob_prod, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_choicedata(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
