# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_softmax <- function(u, log = FALSE) {
    .Call(`_choicedata_cpp_softmax`, u, log)
}

cpp_logsumexp <- function(x) {
    .Call(`_choicedata_cpp_logsumexp`, x)
}

cpp_ologit <- function(v, gamma, y, log = FALSE) {
    .Call(`_choicedata_cpp_ologit`, v, gamma, y, log)
}

cpp_ologit_all <- function(v, gamma) {
    .Call(`_choicedata_cpp_ologit_all`, v, gamma)
}

cpp_ranked_logit <- function(u, ranking, log = FALSE) {
    .Call(`_choicedata_cpp_ranked_logit`, u, ranking, log)
}

cpp_mnl_chosen <- function(x, y, beta, ranked = FALSE, log = FALSE) {
    .Call(`_choicedata_cpp_mnl_chosen`, x, y, beta, ranked, log)
}

cpp_mnl_all <- function(x, beta, log = FALSE) {
    .Call(`_choicedata_cpp_mnl_all`, x, beta, log)
}

cpp_panel_prod <- function(p, tp, log = FALSE, input_log = FALSE) {
    .Call(`_choicedata_cpp_panel_prod`, p, tp, log, input_log)
}

cpp_average_draws <- function(draws, beta, position, compute, log = FALSE) {
    .Call(`_choicedata_cpp_average_draws`, draws, beta, position, compute, log)
}

cpp_probit_d <- function(v, y, ranked) {
    .Call(`_choicedata_cpp_probit_d`, v, y, ranked)
}

cpp_probit_cov <- function(x, omega, sigma, d, occasions) {
    .Call(`_choicedata_cpp_probit_cov`, x, omega, sigma, d, occasions)
}

cpp_cml_chunks <- function(tp, block, type) {
    .Call(`_choicedata_cpp_cml_chunks`, tp, block, type)
}

cpp_prob_prod <- function(p, log = FALSE) {
    .Call(`_choicedata_cpp_prob_prod`, p, log)
}

