# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ologit <- function(x, beta, gamma, y = NULL, log = FALSE) {
    .Call(`_choicedata_cpp_ologit`, x, beta, gamma, y, log)
}

cpp_ranked_logit <- function(u, ranking, log = FALSE) {
    .Call(`_choicedata_cpp_ranked_logit`, u, ranking, log)
}

cpp_mnl_chosen <- function(x, y, beta, ranked = FALSE, log = FALSE, availability = NULL) {
    .Call(`_choicedata_cpp_mnl_chosen`, x, y, beta, ranked, log, availability)
}

cpp_mnl_all <- function(x, beta, log = FALSE, availability = NULL) {
    .Call(`_choicedata_cpp_mnl_all`, x, beta, log, availability)
}

cpp_mmnl <- function(x, y, beta, chol, draws, position, type, tp = NULL, ranked = FALSE, log = FALSE, availability = NULL) {
    .Call(`_choicedata_cpp_mmnl`, x, y, beta, chol, draws, position, type, tp, ranked, log, availability)
}

cpp_softmax <- function(u, log = FALSE) {
    .Call(`_choicedata_cpp_softmax`, u, log)
}

cpp_logsumexp <- function(x) {
    .Call(`_choicedata_cpp_logsumexp`, x)
}

cpp_lc_prob <- function(probs, weights, log = FALSE) {
    .Call(`_choicedata_cpp_lc_prob`, probs, weights, log)
}

cpp_rankings <- function(values, depth) {
    .Call(`_choicedata_cpp_rankings`, values, depth)
}

cpp_panel_prod <- function(p, tp, log = FALSE, input_log = FALSE) {
    .Call(`_choicedata_cpp_panel_prod`, p, tp, log, input_log)
}

cpp_cml_log <- function(probability, tp, type) {
    .Call(`_choicedata_cpp_cml_log`, probability, tp, type)
}

cpp_average_draws <- function(draws, beta, position, compute, log = FALSE, chol = NULL, type = NULL, args = NULL, chunks = NULL) {
    .Call(`_choicedata_cpp_average_draws`, draws, beta, position, compute, log, chol, type, args, chunks)
}

cpp_cml_chunks <- function(tp, block, type) {
    .Call(`_choicedata_cpp_cml_chunks`, tp, block, type)
}

cpp_prob_prod <- function(p, log = FALSE) {
    .Call(`_choicedata_cpp_prob_prod`, p, log)
}

cpp_ordered_probit <- function(x, y, beta, sigma, gamma, omega = NULL, position = NULL, log = FALSE) {
    .Call(`_choicedata_cpp_ordered_probit`, x, y, beta, sigma, gamma, omega, position, log)
}

cpp_binary_probit <- function(x, y, beta, sigma, omega = NULL, position = NULL, log = FALSE, availability = NULL) {
    .Call(`_choicedata_cpp_binary_probit`, x, y, beta, sigma, omega, position, log, availability)
}

cpp_probit_d <- function(v, y, ranked, availability = NULL) {
    .Call(`_choicedata_cpp_probit_d`, v, y, ranked, availability)
}

cpp_probit_cov <- function(x, omega, sigma, d, occasions) {
    .Call(`_choicedata_cpp_probit_cov`, x, omega, sigma, d, occasions)
}

